"""empty message

Revision ID: c7c86dae2a44
Revises: aca1d8d79378
Create Date: 2025-04-03 11:48:09.638019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.url import URLType


# revision identifiers, used by Alembic.
revision: str = "c7c86dae2a44"
down_revision: Union[str, None] = "aca1d8d79378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medeafile",
        sa.Column("file_url", URLType(), nullable=False),
    )
    op.drop_index("ix_medeafile_filename", table_name="medeafile")
    op.drop_column("medeafile", "image_url")
    op.drop_index("ix_user_email", table_name="user")
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    op.add_column(
        "medeafile",
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.create_index(
        "ix_medeafile_filename", "medeafile", ["filename"], unique=False
    )
    op.drop_column("medeafile", "file_url")
    # ### end Alembic commands ###
