"""empty message

Revision ID: 679e28a7b15c
Revises: c7c86dae2a44
Create Date: 2025-04-07 11:06:52.035586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.url import URLType


# revision identifiers, used by Alembic.
revision: str = "679e28a7b15c"
down_revision: Union[str, None] = "c7c86dae2a44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mediafile",
        sa.Column("filename", sa.String(length=100), nullable=False),
        sa.Column("file_url", URLType(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("medeafile")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medeafile",
        sa.Column(
            "filename",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "owner_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("file_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="medeafile_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="medeafile_pkey"),
    )
    op.drop_table("mediafile")
    # ### end Alembic commands ###
