"""empty message

Revision ID: aca1d8d79378
Revises: d9d574fcecf7
Create Date: 2025-04-02 09:31:27.534693

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.url import URLType


# revision identifiers, used by Alembic.
revision: str = "aca1d8d79378"
down_revision: Union[str, None] = "d9d574fcecf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medeafile",
        sa.Column("filename", sa.String(length=100), nullable=False),
        sa.Column("image_url", URLType(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medeafile_filename"), "medeafile", ["filename"], unique=False
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=250), nullable=False
    )
    op.drop_index("ix_user_email", table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=250), nullable=True
    )
    op.drop_index(op.f("ix_medeafile_filename"), table_name="medeafile")
    op.drop_table("medeafile")
    # ### end Alembic commands ###
